GET http://localhost:8080/index





###
POST http://localhost:8080/register
Content-Type: application/json

{
   "e":"6306021610080@fitm.kmutnb.ac.th",
    "password": "pwd2545",
    "name":"พัชรพร มุ่งทวีเกียรติ"

}
    


###
POST http://env-ff.app.ruk-com.cloud/register
Content-Type: application/json


 {
       
   "e":"6306021610010fitm.kmutnb.ac.th",
    "password": "1111",
    "name":"พัชรพร มุ่งทวีเกียรติ"

   
}      
###
POST http://localhost:8080/termgrade1
Content-Type: application/json

{

  "e":"6306021620140@fitm.kmutnb.ac.th",
  "term":1,
  "year":2564,
  
  
  "namesubject1":"060243106   DATA STRUCTURE AND ALGORITHM",
  "unit1":3 ,
  "grade1":2.5,
  
    
  "namesubject2": " 060243107   COMPUTER ARCHITECTURE ",
  "unit2":3,
  "grade2":2.5,
  
    
  "namesubject3":" 060243108   DATABASE SYSTEM",
  "unit3": 3,
  "grade3":3.5,
  
    
  "namesubject4":" 060243109   COMPUTER NETWORK AND COMMUNI",
  "unit4": 3,
  "grade4":4,
  
    
  "namesubject5": " 080303603   PERSONALITY DEVELOPMENT",
  "unit5": 3,
  "grade5":4

  
  
   

  
  
  


  

  
      
  
  
    
}




   

    
  










